### ISSUE TITLE
Chatter のフィード内検索を実行したページに対して，シェア投稿の 1行 表示が実行されていない．

### ISSUE THREAD

**Issue by karma-adc** [TABETA/ChatterExtension#8]
### 概要

Chatter のフィード内検索を実施した結果のページで，シェア投稿した投稿が 1行 表示されていない．

### 補足

フィード内検索
![image](https://github.com/TABETA/ChatterExtension/assets/161335247/cc4dfe11-e141-471d-90f7-a5149c098057)

**Comment by TABETA** [comment]
ありがとうございます。
現象確認しましたが恐らく #1 と同じ現象と思われます。
対策を検討いたします。

**Comment by TABETA** [comment]
@karma-adc 
V1.1.1で修正しました。直っていないようでしたらご連絡いただけますと幸いです。
https://github.com/TABETA/ChatterExtension/releases/tag/v1.1.1

**Comment by TABETA** [comment]
すみません、#1とは異なる現象であることを理解しました。再オープンします。

**Comment by TABETA** [comment]
@karma-adc
V1.1.2で修正しました。

**Comment by karma-adc** [comment]
ありがとうございます！ @TABETA 
思った表示になっていることを確認できました．
